# Site settings
title: JackBtype's Blog
email: qq1998800@163.com
description: "JackBtype's Blog"
keyword: ""
url: "https://Jack-btype.github.io"              # your host, for absolute URL
baseurl: ""                            # for example, '/blog' if your blog hosted on 'host/blog'
manager: JackBtype

#authors' information
#use site.authors[page.author].name to access the author's name
authors:
  Mensu:
    name: JackBtype
    email: qq1998800@163.com
    website: https://jack-btype.github.io
    github: Jack-btype
    
SNS:
  - site: github
    username: Jack-btype
    url: https://github.com/Jack-btype

# Build settings
gems: [jekyll-paginate]
paginate: 2
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: highlight

# Disqus settings
#disqus-username:

# Duoshuo settings
# duoshuo-username: jackbtype
# Share component is depend on Comment so we can NOT use share only.
# duoshuo-share: false                     # set to false if you want to use Comment without Sharing

# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
ga_track_id:          # Format: UA-xxxxxx-xx
ga_domain:

anchorjs: true                          # if you want to customize anchor. check out line:? of `post.html`
sidenav: true
mathjax: true

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar:      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: -1              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    # {
    #     title: "Hux Blog",
    #     href: "http://huangxuan.me"
    # },{
    #     title: "Foo",
    #     href: "#"
    # },{
    #     title: "Bar",
    #     href: "#"
    # },{
    #     title: "Example Friends",
    #     href: "#"
    # },{
    #     title: "It helps SEO",
    #     href: "#"
    # }
]
