# Site settings
title: Mensu - 思考のかけら
SEOTitle: Mensu - 思考のかけら | fragments of thought
email: yxshw55@qq.com
description: "Mensu's Blog"
keyword: ""
url: "https://mensu.github.io"              # your host, for absolute URL
baseurl: ""                            # for example, '/blog' if your blog hosted on 'host/blog'
manager: Mensu

#authors' information
#use site.authors[page.author].name to access the author's name
authors:
  Mensu:
    name: Mensu
    email: yxshw55@qq.com
    website: https://mensu.github.io
    github: Mensu
    weibo: yxshw55
    twitter: mensuhamesu
    QQ: 805495207

SNS: 
  - site: github
    username: Mensu
    url: https://github.com/Mensu

  - site: weibo
    username: yxshw55
    url: http://weibo.com/yxshw55

  - site: twitter
    username: mensuhamesu
    url: https://twitter.com/mensuhamesu

# Build settings
gems: [jekyll-paginate]
paginate: 2
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  # syntax_highlighter: highlightjs
  # syntax_highlighter_opts:
  #   default_lang: "ruby"

# Disqus settings
#disqus-username: 

# Duoshuo settings
duoshuo-username: mensu
# Share component is depend on Comment so we can NOT use share only.
duoshuo-share: true                     # set to false if you want to use Comment without Sharing

# Analytics settings
# Baidu Analytics
ba_track_id: 
# Google Analytics
ga_track_id:          # Format: UA-xxxxxx-xx
ga_domain: 

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: "https://mensu.github.io/img/avatar.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: -1              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    # {
    #     title: "Hux Blog",
    #     href: "http://huangxuan.me"
    # },{
    #     title: "Foo",
    #     href: "#"
    # },{
    #     title: "Bar",
    #     href: "#"
    # },{
    #     title: "Example Friends",
    #     href: "#"
    # },{
    #     title: "It helps SEO",
    #     href: "#"
    # }
]
